#include <cairo.h>

#include "fonts.h"

const char MONO[] = "Mono";
const char ARIAL[] = "Arial";

struct font_style font_table[] = {
	{FONT_FIELD_LABEL,       0.0, 1.0, 1.0, MONO,  14, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_FIELD_VALUE,       1.0, 1.0, 1.0, MONO,  14, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_LARGE_FIELD,       0.0, 1.0, 1.0, MONO,  18, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_LARGE_VALUE,       1.0, 1.0, 1.0, ARIAL, 14, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_SMALL,             0.0, 1.0, 1.0, MONO,  10, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_LOG,               1.0, 1.0, 1.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_FT8_RX,            0.0, 1.0, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_FT8_TX,            1.0, 0.6, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_SMALL_FIELD_VALUE, 1.0, 1.0, 1.0, MONO,  11, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_CW_RX,             0.0, 1.0, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_CW_TX,             1.0, 0.6, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_FLDIGI_RX,         0.0, 1.0, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_FLDIGI_TX,         1.0, 0.6, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_TELNET,            0.0, 1.0, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
	{FONT_FT8_QUEUED,        1.0, 0.6, 0.0, MONO,  12, CAIRO_FONT_WEIGHT_NORMAL, CAIRO_FONT_SLANT_NORMAL},
};

const int FONT_COUNT = sizeof(font_table)/sizeof(struct font_style);