char *help_text = 
    "Help\r\n\r\n"
    "\\audio\r\n"
    "\\callsign [your callsign]\r\n"
    "\\clear - clear the console display\r\n"
    "\\cwinput [key|keyer|kbd]\r\n"
    "\\cwdelay\r\n"
    "\\cw_tx_pitch\r\n"
    "\\exchange\r\n"
    "\\freq\r\n"
    "\\ft8mode [auto|semiauto|manual]\r\n"
    "\\grid [your grid]\r\n"
    "\\l [callsign] [rst]\r\n"
    "\\logbook\r\n"
    "\\macro [macro name]\r\n"
    "\\mode [CW|CWR|USB|LSB|RTTY|FT8|DIGITAL|2TONE]\r\n"
    "\\qrz [callsign]\r\n"
    "\\r - receive\r\n"
    "\\sidetone\r\n"
    "\\t - transmit\r\n"
    "\\telnet [server]:[port]\r\n"
    "\\tclose - close telnet session\r\n"
    "\\txpitch [100-3000]\r\n"
    "\\wpm [cw words per minute]\r\n"
    "Do \\h2 command for help page 2...\r\n";

char *help2_text = 
    "Help - Page 2\r\n\r\n"
    "\\exit\r\n\r\n"
    "\\s - view settings\r\n"
    "\\mp [BLANK|LEFT|RIGHT|CROSSHAIR] - mouse pointer style\r\n"
    "\\rs [ON|OFF] - reverse scrolling\r\n\r\n"
    "\\ta [ON|OFF] - Turns tuning acceleration on and off\r\n"
    "\\txcal {V2 only} - transmit power calibration\r\n"
    "\\metercal - meter calibration\r\n"
    "\\tat1 [100-99999] - 1st threshold acceleration\r\n     (default: 10,000)\r\n"
    "\\tat2 [100-99999] - 2nd threshold acceleration\r\n     (default: 500)\r\n\r\n"
    "\\cw \\cwr \\usb \\lsb \\rtty \\ft8 \\digital \\dig \\2tone\r\n";

